spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root


springdoc:
  api-docs:
      path: /api-docs
  swagger-ui:
    operations-sorter: method
#    path: /swagger-ui-custom.html
#    swagger ui
#  mvc:

#    pathmatch:
#      matching-strategy: ant_path_matcher
#      